version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  # uf1:
  #   networks:
  #     splunknet:
  #       aliases:
  #         - uf1
  #   image: ${UF_IMAGE:-splunk/universalforwarder:latest}
  #   hostname: uf1
  #   container_name: uf1
  #   environment:
  #     - SPLUNK_START_ARGS=--accept-license
  #     - SPLUNK_STANDALONE_URL=so1
  #     - SPLUNK_ADD=udp 1514,monitor /var/log/*
  #     - SPLUNK_PASSWORD=password
  #   ports:
  #     - 8089
  #   volumes:
  #     - app-volume:/var/log


  so1:
    networks:
      splunknet:
        aliases:
          - so1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    hostname: so1
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_STANDALONE_URL=so1
      - SPLUNK_PASSWORD=password
    ports:
      - "8000:8000"
      - "8089:8089"
    volumes:
      - app-volume:/tmp/log


  log-gen:
      image: ubuntu
      command: /bin/bash -c "while true; do echo `date` >> /var/log/log; sleep 1; done;"
      volumes:
          - app-volume:/var/log



volumes:
     app-volume: 